apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  name: slam-autoscale
  labels: 
    app: autoscale
    node: slam
spec: 
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
    type: Resource
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: turtlebot3-slam
  