apiVersion: apps/v1
kind: Deployment
metadata:
  name: turtlebot3-slam
  labels:
    app: ros1
    node: slam
spec:
  replicas: 1
  selector: 
    matchLabels:
      node: slam
  template:
    metadata:
      labels:
        node: slam
    spec:
      containers:
      - name: slam
        tty: true
        image: namgungjaeseon/ros-noetic
        command: ["/bin/bash", "-c"]
        args: ["source /opt/ros/noetic/setup.bash && source ~/catkin_ws/devel/setup.bash && export TURTLEBOT3_MODEL=burger && roslaunch turtlebot3_slam turtlebot3_slam.launch"]
        imagePullPolicy: IfNotPresent
        tty: true
        env:
        - name: ROS_MASTER_URI
          value: http://rosmaster-service:11311
        - name: ROS_HOSTNAME
          value: slam-service
        - name: DISPLAY
          value: "172.20.69.111:0"
        volumeMounts:
        - name: x11-socket
          mountPath: /tmp/.X11-unix
        resources:
          requests: # metrics로 참조할 cpu사용률
            cpu: 50m
          limits:
            cpu: 100m
      volumes:
      - name: x11-socket
        hostPath:
          path: /tmp/.X11-unix
          type: Directory
---   
apiVersion: v1
kind: Service
metadata: 
  name: slam-service
  labels:
    app: ros1
    node: slam
spec:
  clusterIP: None
  selector: 
    node: slam